# ====================================================
#         __                   __ __   __
# .---.-.|  |.---.-.----.----.|__|  |_|  |_.--.--.
# |  _  ||  ||  _  |  __|   _||  |   _|   _|  |  |
# |___._||__||___._|____|__|  |__|____|____|___  |
#                                          |_____|
#              __
# .----.-----.|  |.-----.----.-----.
# |  __|  _  ||  ||  _  |   _|__ --|
# |____|_____||__||_____|__| |_____|
# ====================================================

# Alacritty colors config machinepwn...
# Usergh0st = [ https://github.com/Usergh0st/Machinepwn.git ]
# 16.12.2025 10:38 AM

# The color config dot.
# config = [ https://alacritty.org/config-alacritty.html#colors ]

# Default colors
[colors.primary]
foreground = "#cd9191"
background = "#0f0f0f"

# Cursor colors
[colors.cursor]
text = "#812625" 
cursor = "#261314"

# Vi colors
[colors.vi_mode_cursor]
text = "#cd9191"
cursor = "#261314"

# Normal colors
[colors.normal]
black = "#4A201F"
red = "#4B1F20"
green = "#4F2425"
yellow = "#732526"
blue = "#474447"
magenta = "#882726"
cyan = "#cd9191"
white = "#8f6565"

# Bright colors
[colors.bright]
black = "#4A201F"
red = "#261314"
green = "#4B1F20"
yellow = "#4F2425"
blue = "#732526"
magenta = "#474447"
cyan = "#882726"
white = "#cd9191"
