#         __                   __ __   __
# .---.-.|  |.---.-.----.----.|__|  |_|  |_.--.--.
# |  _  ||  ||  _  |  __|   _||  |   _|   _|  |  |
# |___._||__||___._|____|__|  |__|____|____|___  |
#                                          |_____|
#   ___               __
# .'  _|.-----.-----.|  |_.-----.
# |   _||  _  |     ||   _|__ --|
# |__|  |_____|__|__||____|_____|

# Alacritty fonts config machinepwn...
# Usergh0st = [ https://github.com/Usergh0st/Machinepwn.git ]
# 16.12.2025 11:06 AM

# Alacritty fonts configuration.
# Config = [ https://alacritty.org/config-alacritty.html#font ]

[font]
size = 12
builtin_box_drawing  = true

[font.normal]
#normal = { family = "Cascadia Code", style = "Regular" }
#bold = { family = "Cascadia Code", style = "Bold" }
#italic = { family = "Cascadia Code", style = "Italic"}
family = "Cascadia Code"
